"""
Download Historical — OHLCV + Macro TimescaleDB Loader
========================================================
CLI script to populate TimescaleDB with historical OHLCV and macro data.

Usage:
    python -m backend.scripts.download_historical \\
        --tickers SPY,QQQ,AAPL,NVDA \\
        --tf 1d,1h \\
        --years 5 \\
        --include-macro

Harmonization Rules Applied:
- R1: All timestamps converted to UTC
- R2: Columns normalized to lowercase (open, high, low, close, volume)
- R7: Append-only with deduplication (ON CONFLICT DO NOTHING)

Note: Weekly candles are auto-generated by TimescaleDB continuous aggregates.
"""
import argparse
import logging
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd

# Add project root to path
_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_root))

# Load .env for POSTGRES_URL
from dotenv import load_dotenv
load_dotenv(_root / ".env")

from backend.modules.shared.infrastructure.timescale_data_store import TimescaleDataStore

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(message)s")


def harmonize_yfinance(df: pd.DataFrame, ticker: str) -> pd.DataFrame:
    """Apply harmonization rules R1 + R2 to yfinance DataFrame."""
    if df.empty:
        return df

    # Flatten MultiIndex if present (yfinance multi-ticker download)
    if isinstance(df.columns, pd.MultiIndex):
        df = df.xs(ticker, level=1, axis=1)

    # R2: lowercase columns
    df.columns = [c.lower() for c in df.columns]

    # Keep only OHLCV
    required = ["open", "high", "low", "close", "volume"]
    available = [c for c in required if c in df.columns]
    df = df[available].copy()

    # R1: convert to UTC
    if df.index.tz is not None:
        df.index = df.index.tz_convert("UTC")
    else:
        df.index = df.index.tz_localize("UTC")

    df.index.name = "timestamp"

    # Dtypes
    for col in ["open", "high", "low", "close"]:
        if col in df.columns:
            df[col] = df[col].astype("float64")
    if "volume" in df.columns:
        df["volume"] = df["volume"].fillna(0).astype("int64")

    # Drop rows with NaN OHLC
    df.dropna(subset=["open", "high", "low", "close"], inplace=True)

    return df


def enrich_with_alpaca(ticker: str, start, end, store: TimescaleDataStore) -> int:
    """Enrich existing bars with trade_count + vwap from Alpaca SDK."""
    import os
    from datetime import datetime, UTC

    api_key = os.environ.get("ALPACA_API_KEY", "")
    if not api_key:
        logger.debug("ALPACA_API_KEY not set — skipping enrichment")
        return 0

    try:
        from alpaca.data.historical import StockHistoricalDataClient
        from alpaca.data.requests import StockBarsRequest
        from alpaca.data.timeframe import TimeFrame

        client = StockHistoricalDataClient(
            api_key, os.environ.get("ALPACA_SECRET_KEY", "")
        )
        request = StockBarsRequest(
            symbol_or_symbols=ticker,
            timeframe=TimeFrame.Day,
            start=datetime.combine(start, datetime.min.time()).replace(tzinfo=UTC),
            end=datetime.combine(end, datetime.max.time()).replace(tzinfo=UTC),
            limit=10000,
        )
        bars = client.get_stock_bars(request)
        if not bars or ticker not in bars.data:
            return 0

        conn = store._conn()
        updated = 0
        try:
            with conn.cursor() as cur:
                for bar in bars.data[ticker]:
                    vwap = float(bar.vwap) if hasattr(bar, 'vwap') and bar.vwap else None
                    tc = int(bar.trade_count) if hasattr(bar, 'trade_count') and bar.trade_count else None
                    if vwap is None and tc is None:
                        continue
                    cur.execute(
                        """UPDATE market.ohlcv_bars
                           SET vwap = %s, trade_count = %s
                           WHERE ticker = %s AND timeframe = '1d'
                           AND time::date = %s""",
                        (vwap, tc, ticker, bar.timestamp.date()),
                    )
                    updated += cur.rowcount
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            store._put(conn)

        if updated > 0:
            logger.info(f"  ↳ Alpaca enrichment: {updated} bars got trade_count + vwap")
        return updated

    except ImportError:
        logger.debug("alpaca-py not installed — skipping enrichment")
        return 0
    except Exception as e:
        logger.warning(f"  ↳ Alpaca enrichment failed for {ticker}: {e}")
        return 0


def download_ticker(ticker: str, tf: str, years: int, store: TimescaleDataStore) -> int:
    """Download and vault a single ticker/timeframe."""
    try:
        import yfinance as yf
    except ImportError:
        logger.error("yfinance not installed: pip install yfinance")
        return 0

    # Check last date for incremental download
    last_date = store.bars_last_date(ticker, tf)

    if last_date:
        start_dt = last_date + timedelta(days=1)
        period = None
        start_str = start_dt.strftime("%Y-%m-%d")
        logger.info(f"Incremental: {ticker}/{tf} from {start_str}")
        df = yf.download(
            ticker, start=start_str,
            interval=tf, progress=False, auto_adjust=True,
        )
    else:
        if tf == "1h":
            # Yahoo limits 1h to ~730 days
            period = "730d"
        else:
            period = f"{years}y"
        logger.info(f"Full download: {ticker}/{tf} period={period}")
        df = yf.download(
            ticker, period=period,
            interval=tf, progress=False, auto_adjust=True,
        )

    if df.empty:
        logger.warning(f"No data returned for {ticker}/{tf}")
        return 0

    df = harmonize_yfinance(df, ticker)
    store.save_bars(ticker, tf, df)

    # Enrich with Alpaca trade_count + vwap (yfinance doesn't provide these)
    if tf == "1d":
        first_date = df.index.min().date() if hasattr(df.index.min(), 'date') else df.index.min()
        last_date = df.index.max().date() if hasattr(df.index.max(), 'date') else df.index.max()
        enrich_with_alpaca(ticker, first_date, last_date, store)

    return len(df)


def download_macro(store: TimescaleDataStore) -> None:
    """Download VIX and yield curve data."""
    try:
        import yfinance as yf
    except ImportError:
        logger.error("yfinance not installed")
        return

    # VIX
    logger.info("Downloading VIX...")
    vix = yf.download("^VIX", period="5y", interval="1d", progress=False)
    if not vix.empty:
        vix = harmonize_yfinance(vix, "^VIX")
        store.save_macro("vix", vix)
        logger.info(f"VIX: {len(vix)} bars saved")

    # Yields
    logger.info("Downloading yields (TNX, IRX)...")
    tnx = yf.download("^TNX", period="5y", interval="1d", progress=False)
    irx = yf.download("^IRX", period="5y", interval="1d", progress=False)

    if not tnx.empty and not irx.empty:
        tnx = harmonize_yfinance(tnx, "^TNX")
        irx = harmonize_yfinance(irx, "^IRX")
        yields = pd.DataFrame({
            "yield_10y": tnx["close"],
            "yield_3m": irx["close"],
        }).dropna()
        store.save_macro("yields", yields)
        logger.info(f"Yields: {len(yields)} bars saved")


# resample_timeframes removed — TimescaleDB continuous aggregates
# auto-generate weekly candles from daily data (market.ohlcv_weekly).


def main():
    parser = argparse.ArgumentParser(description="Download historical data to vault")
    parser.add_argument("--tickers", required=True, help="Comma-separated tickers")
    parser.add_argument("--tf", default="1d", help="Comma-separated timeframes (1d,1h)")
    parser.add_argument("--years", type=int, default=5, help="Years of history for 1d")
    parser.add_argument("--include-macro", action="store_true", help="Also download VIX, yields")
    args = parser.parse_args()

    store = TimescaleDataStore()
    tickers = [t.strip().upper() for t in args.tickers.split(",")]
    timeframes = [t.strip() for t in args.tf.split(",")]

    total_bars = 0
    for ticker in tickers:
        for tf in timeframes:
            n = download_ticker(ticker, tf, args.years, store)
            total_bars += n



    if args.include_macro:
        download_macro(store)

    logger.info(f"✅ Download complete: {total_bars} total bars across {len(tickers)} tickers")


if __name__ == "__main__":
    main()
