"""
High Yield Corporate Credit Stress (CREDIT) Fact Store Lookup Adapter — Pure Domain Rule
========================================================================================
Provides lag-free real-time lookup against credit_fact_store.json.
Queries 7x7 3-Day Fast Kinematic Velocity (Delta 3d - 72h) credit stress stereotypes.
"""
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, Optional

FACT_STORE_PATH = Path(__file__).parent / "credit_fact_store.json"


@dataclass(frozen=True)
class CreditScaleGuidance:
    p_bull: float
    p_bear: float
    e_ret_max: float
    e_ret_min: float
    ev_net: float
    e_days: float
    ev_per_day: float
    rr_asymmetry: float


@dataclass(frozen=True)
class CreditStateGuidance:
    state_key: str
    credit_bin: str
    velocity_vector: str
    n: int
    credit_ratio_mean: float
    credit_ratio_std: float
    divergence_regime: str
    operational_guidance: str
    zz25: CreditScaleGuidance
    zz50: CreditScaleGuidance
    zz75: CreditScaleGuidance

    @property
    def ev_per_day_50(self) -> float:
        """Returns the primary capital velocity (% return per trading day at 5% scale)."""
        return self.zz50.ev_per_day

    def to_vector(self) -> Dict[str, Any]:
        """
        Converts state guidance into a compact feature vector for direct 
        consumption by QualityEntryGate, SpeculativeEntryHub, and CIO Allocator.
        """
        return {
            "state_key": self.state_key,
            "credit_bin": self.credit_bin,
            "velocity_vector": self.velocity_vector,
            "n_samples": self.n,
            "divergence_regime": self.divergence_regime,
            "operational_guidance": self.operational_guidance,
            # Probabilities vector
            "p_bull": [self.zz25.p_bull, self.zz50.p_bull, self.zz75.p_bull],
            "p_bear": [self.zz25.p_bear, self.zz50.p_bear, self.zz75.p_bear],
            # EV Net Vector
            "ev_net": [self.zz25.ev_net, self.zz50.ev_net, self.zz75.ev_net],
            # Timelines Vector (Trading Days)
            "e_days": [self.zz25.e_days, self.zz50.e_days, self.zz75.e_days],
            # Time-Independent Capital Velocity Vector (% / day)
            "ev_per_day": [self.zz25.ev_per_day, self.zz50.ev_per_day, self.zz75.ev_per_day],
            # Primary 5% Scale Values
            "primary_p_bull": self.zz50.p_bull,
            "primary_ev_net": self.zz50.ev_net,
            "primary_e_days": self.zz50.e_days,
            "primary_capital_velocity": self.zz50.ev_per_day,
        }


class CreditLookupAdapter:
    """Loads and queries the trained empirical Credit Stress Fact Store."""

    def __init__(self, fact_store_path: Optional[Path] = None):
        target_path = fact_store_path or FACT_STORE_PATH
        if not target_path.exists():
            raise FileNotFoundError(
                f"STRICT DATA POLICY: Missing required Fact Store {target_path}. "
                "The file must be generated by backend.scripts.generate_credit_fact_table first."
            )

        with open(target_path, "r", encoding="utf-8") as f:
            self._data = json.load(f)

        doc = self._data.get("_documentation", {})
        thresh = doc.get("dimension_thresholds_definition", {})
        self.credit_edges = thresh.get("credit_edges", [])
        self.credit_speed_edges = thresh.get("credit_speed_edges", [])
        self.states = self._data.get("states", {})

    def _classify_bin(self, v: float) -> str:
        labels = [
            "EXTREME_CREDIT_FREEZE",
            "CREDIT_STRESS_HIGH",
            "CREDIT_STRESS_MODERATE",
            "NEUTRAL_CREDIT",
            "HEALTHY_CREDIT",
            "EXPANSIVE_CREDIT",
            "MAX_CREDIT_EXPANSION",
        ]
        for idx, e in enumerate(self.credit_edges):
            if v < e:
                return labels[idx]
        return labels[-1]

    def _classify_speed(self, v: float) -> str:
        labels = [
            "EXTREME_CREDIT_CRASH_3D",
            "FAST_CREDIT_DETERIORATION_3D",
            "DECELERATING_CREDIT_3D",
            "STABLE_CREDIT_3D",
            "EXPANDING_CREDIT_3D",
            "FAST_CREDIT_RECOVERY_3D",
            "EXTREME_CREDIT_SURGE_3D",
        ]
        for idx, e in enumerate(self.credit_speed_edges):
            if v < e:
                return labels[idx]
        return labels[-1]

    def lookup_credit_guidance(
        self, credit_ratio: float, credit_d3: float
    ) -> Optional[CreditStateGuidance]:
        """
        Determines the 3-day fast credit-velocity state key dynamically and returns
        the corresponding EV expectations, regime rules, and capital velocity.
        """
        credit_bin = self._classify_bin(credit_ratio)
        credit_speed = self._classify_speed(credit_d3)

        state_key = f"{credit_bin}__{credit_speed}"
        state = self.states.get(state_key)

        if not state:
            return None

        def _make_scale(d: dict) -> CreditScaleGuidance:
            return CreditScaleGuidance(
                p_bull=d["p_bull"],
                p_bear=d["p_bear"],
                e_ret_max=d["e_ret_max"],
                e_ret_min=d["e_ret_min"],
                ev_net=d["ev_net"],
                e_days=d["e_days"],
                ev_per_day=d["ev_per_day"],
                rr_asymmetry=d["rr_asymmetry"],
            )

        t0_stats = state.get("credit_ratio_t0_stats", {})

        return CreditStateGuidance(
            state_key=state_key,
            credit_bin=credit_bin,
            velocity_vector=credit_speed,
            n=state["n"],
            credit_ratio_mean=t0_stats.get("mean", credit_ratio),
            credit_ratio_std=t0_stats.get("std", 0.0),
            divergence_regime=state["divergence_regime"],
            operational_guidance=state["operational_guidance"],
            zz25=_make_scale(state["zz25"]),
            zz50=_make_scale(state["zz50"]),
            zz75=_make_scale(state["zz75"]),
        )


credit_lookup = CreditLookupAdapter()
