"""
Fear & Greed Index Fact Store Lookup Adapter — Pure Domain Rule
=============================================================
Provides lag-free real-time lookup against fg_fact_store.json.
Queries 7x7 3-Day Fast Kinematic Velocity (Delta 3d - 72h) sentiment stereotypes.
"""
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, Optional

FACT_STORE_PATH = Path(__file__).parent / "fg_fact_store.json"

@dataclass(frozen=True)
class ScaleGuidance:
    p_bull: float
    p_bear: float
    e_ret_max: float
    e_ret_min: float
    ev_net: float
    e_days: float
    ev_per_day: float
    rr_asymmetry: float

@dataclass(frozen=True)
class FGStateGuidance:
    state_key: str
    sentiment_bin: str
    velocity_vector: str
    n: int
    fg_mean: float
    fg_std: float
    divergence_regime: str
    operational_guidance: str
    zz25: ScaleGuidance
    zz50: ScaleGuidance
    zz75: ScaleGuidance

    @property
    def ev_per_day_50(self) -> float:
        """Returns the primary capital velocity (% return per trading day at 5% scale)."""
        return self.zz50.ev_per_day

    def to_vector(self) -> Dict[str, Any]:
        """
        Converts state guidance into a compact feature vector for direct 
        consumption by QualityEntryGate, SpeculativeEntryHub, and CIO Allocator.
        """
        return {
            "state_key": self.state_key,
            "sentiment_bin": self.sentiment_bin,
            "velocity_vector": self.velocity_vector,
            "n_samples": self.n,
            "divergence_regime": self.divergence_regime,
            "operational_guidance": self.operational_guidance,
            # Probabilities vector
            "p_bull": [self.zz25.p_bull, self.zz50.p_bull, self.zz75.p_bull],
            "p_bear": [self.zz25.p_bear, self.zz50.p_bear, self.zz75.p_bear],
            # EV Net Vector
            "ev_net": [self.zz25.ev_net, self.zz50.ev_net, self.zz75.ev_net],
            # Timelines Vector (Trading Days)
            "e_days": [self.zz25.e_days, self.zz50.e_days, self.zz75.e_days],
            # Time-Independent Capital Velocity Vector (% / day)
            "ev_per_day": [self.zz25.ev_per_day, self.zz50.ev_per_day, self.zz75.ev_per_day],
            # Primary 5% Scale Values
            "primary_p_bull": self.zz50.p_bull,
            "primary_ev_net": self.zz50.ev_net,
            "primary_e_days": self.zz50.e_days,
            "primary_capital_velocity": self.zz50.ev_per_day
        }

class FGLookupAdapter:
    """Loads and queries the trained empirical Fear & Greed Fact Store."""
    
    def __init__(self):
        if not FACT_STORE_PATH.exists():
            raise FileNotFoundError(
                f"STRICT DATA POLICY: Missing required Fact Store {FACT_STORE_PATH}. "
                "The file must be generated by backend.scripts.generate_fg_fact_table first."
            )
            
        with open(FACT_STORE_PATH, "r", encoding="utf-8") as f:
            self._data = json.load(f)
            
        doc = self._data.get("_documentation", {})
        self.fg_edges = doc.get("dimension_thresholds_definition", {}).get("fg_edges", [])
        self.fg_speed_edges = doc.get("dimension_thresholds_definition", {}).get("fg_speed_edges", [])
        self.states = self._data.get("states", {})
        
    def _classify_bin(self, v: float) -> str:
        labels = ["DEEP_FEAR", "EXTREME_FEAR", "FEAR", "NEUTRAL", "GREED", "EXTREME_GREED", "EUPHORIA"]
        for idx, e in enumerate(self.fg_edges):
            if v < e: return labels[idx]
        return labels[-1]

    def _classify_speed(self, v: float) -> str:
        labels = [
            "COLLAPSING_EXTREME_3D",
            "COLLAPSING_FAST_3D",
            "FALLING_3D",
            "STABLE_3D",
            "RISING_3D",
            "RISING_FAST_3D",
            "SURGING_EXTREME_3D"
        ]
        for idx, e in enumerate(self.fg_speed_edges):
            if v < e: return labels[idx]
        return labels[-1]

    def lookup_fg_guidance(
        self,
        fg_val: float,
        fg_d3: float
    ) -> Optional[FGStateGuidance]:
        """
        Determines the 3-day fast sentiment-velocity state key dynamically and returns
        the corresponding EV expectations, regime rules, and capital velocity.
        """
        fg_bin = self._classify_bin(fg_val)
        fg_speed = self._classify_speed(fg_d3)
        
        state_key = f"{fg_bin}__{fg_speed}"
        state = self.states.get(state_key)
        
        if not state:
            return None
            
        def _make_scale(d: dict) -> ScaleGuidance:
            return ScaleGuidance(
                p_bull=d["p_bull"],
                p_bear=d["p_bear"],
                e_ret_max=d["e_ret_max"],
                e_ret_min=d["e_ret_min"],
                ev_net=d["ev_net"],
                e_days=d["e_days"],
                ev_per_day=d["ev_per_day"],
                rr_asymmetry=d["rr_asymmetry"]
            )
            
        return FGStateGuidance(
            state_key=state_key,
            sentiment_bin=fg_bin,
            velocity_vector=fg_speed,
            n=state["n"],
            fg_mean=state["fg_t0_stats"]["mean"],
            fg_std=state["fg_t0_stats"]["std"],
            divergence_regime=state["divergence_regime"],
            operational_guidance=state["operational_guidance"],
            zz25=_make_scale(state["zz25"]),
            zz50=_make_scale(state["zz50"]),
            zz75=_make_scale(state["zz75"])
        )

# Global singleton instance
fg_lookup = FGLookupAdapter()
