"""
Institutional Volume Turbulence (SV5_TURBULENCE) Fact Store Lookup Adapter — Pure Domain Rule
==============================================================================================
Provides lag-free real-time lookup against sv5_turbulence_fact_store.json.
Queries 7x7 3-Day Fast Kinematic Velocity (Delta 3d - 72h) volume turbulence stereotypes.
"""
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, Optional

FACT_STORE_PATH = Path(__file__).parent / "sv5_turbulence_fact_store.json"


@dataclass(frozen=True)
class ScaleGuidance:
    p_bull: float
    p_bear: float
    e_ret_max: float
    e_ret_min: float
    ev_net: float
    e_days: float
    ev_per_day: float
    rr_asymmetry: float


@dataclass(frozen=True)
class SV5TurbulenceStateGuidance:
    state_key: str
    turbulence_bin: str
    velocity_vector: str
    n: int
    turbulence_mean: float
    turbulence_std: float
    divergence_regime: str
    operational_guidance: str
    zz25: ScaleGuidance
    zz50: ScaleGuidance
    zz75: ScaleGuidance

    @property
    def ev_per_day_50(self) -> float:
        """Returns the primary capital velocity (% return per trading day at 5% scale)."""
        return self.zz50.ev_per_day

    def to_vector(self) -> Dict[str, Any]:
        """
        Converts state guidance into a compact feature vector for direct 
        consumption by QualityEntryGate, SpeculativeEntryHub, and CIO Allocator.
        """
        return {
            "state_key": self.state_key,
            "turbulence_bin": self.turbulence_bin,
            "velocity_vector": self.velocity_vector,
            "n_samples": self.n,
            "divergence_regime": self.divergence_regime,
            "operational_guidance": self.operational_guidance,
            # Probabilities vector
            "p_bull": [self.zz25.p_bull, self.zz50.p_bull, self.zz75.p_bull],
            "p_bear": [self.zz25.p_bear, self.zz50.p_bear, self.zz75.p_bear],
            # EV Net Vector
            "ev_net": [self.zz25.ev_net, self.zz50.ev_net, self.zz75.ev_net],
            # Timelines Vector (Trading Days)
            "e_days": [self.zz25.e_days, self.zz50.e_days, self.zz75.e_days],
            # Time-Independent Capital Velocity Vector (% / day)
            "ev_per_day": [self.zz25.ev_per_day, self.zz50.ev_per_day, self.zz75.ev_per_day],
            # Primary 5% Scale Values
            "primary_p_bull": self.zz50.p_bull,
            "primary_ev_net": self.zz50.ev_net,
            "primary_e_days": self.zz50.e_days,
            "primary_capital_velocity": self.zz50.ev_per_day
        }


class SV5TurbulenceLookupAdapter:
    """Loads and queries the trained empirical SV5_TURBULENCE Fact Store."""

    def __init__(self):
        if not FACT_STORE_PATH.exists():
            raise FileNotFoundError(
                f"STRICT DATA POLICY: Missing required Fact Store {FACT_STORE_PATH}. "
                "The file must be generated by backend.scripts.generate_sv5_turbulence_fact_table first."
            )

        with open(FACT_STORE_PATH, "r", encoding="utf-8") as f:
            self._data = json.load(f)

        doc = self._data.get("_documentation", {})
        thresh = doc.get("dimension_thresholds_definition", {})
        self.turbulence_edges = thresh.get("turbulence_edges", [])
        self.turbulence_speed_edges = thresh.get("turbulence_speed_edges", [])
        self.labels_l0 = thresh.get("turbulence_labels_l0", [
            "DEEP_SERENITY",
            "SERENE_VOLUME",
            "NORMAL_PARTICIPATION",
            "ELEVATED_PARTICIPATION",
            "HIGH_VOLUME_TURBULENCE",
            "EXTREME_TURBULENCE_SHOCK",
            "CRISIS_TURBULENCE_VETO"
        ])
        self.labels_l1 = thresh.get("turbulence_labels_l1", [
            "EXTREME_TURBULENCE_CRUSH_3D",
            "TURBULENCE_DECAY_3D",
            "DECELERATING_3D",
            "STABLE_3D",
            "RISING_3D",
            "TURBULENCE_SURGE_3D",
            "EXTREME_TURBULENCE_SPIKE_3D"
        ])
        self.states = self._data.get("states", {})

    def _classify_bin(self, v: float) -> str:
        for idx, e in enumerate(self.turbulence_edges):
            if v < e:
                return self.labels_l0[idx]
        return self.labels_l0[-1]

    def _classify_speed(self, v: float) -> str:
        for idx, e in enumerate(self.turbulence_speed_edges):
            if v < e:
                return self.labels_l1[idx]
        return self.labels_l1[-1]

    def lookup_sv5_turbulence_guidance(
        self,
        turbulence_val: float,
        turbulence_d3: float
    ) -> Optional[SV5TurbulenceStateGuidance]:
        """
        Determines the 3-day fast turbulence-velocity state key dynamically and returns
        the corresponding EV expectations, regime rules, and capital velocity.
        """
        turb_bin = self._classify_bin(turbulence_val)
        turb_speed = self._classify_speed(turbulence_d3)

        state_key = f"{turb_bin}__{turb_speed}"
        state = self.states.get(state_key)

        if not state:
            return None

        def _make_scale(d: dict) -> ScaleGuidance:
            return ScaleGuidance(
                p_bull=d["p_bull"],
                p_bear=d["p_bear"],
                e_ret_max=d["e_ret_max"],
                e_ret_min=d["e_ret_min"],
                ev_net=d["ev_net"],
                e_days=d["e_days"],
                ev_per_day=d["ev_per_day"],
                rr_asymmetry=d["rr_asymmetry"]
            )

        return SV5TurbulenceStateGuidance(
            state_key=state_key,
            turbulence_bin=turb_bin,
            velocity_vector=turb_speed,
            n=state["n"],
            turbulence_mean=state["turbulence_t0_stats"]["mean"],
            turbulence_std=state["turbulence_t0_stats"]["std"],
            divergence_regime=state["divergence_regime"],
            operational_guidance=state["operational_guidance"],
            zz25=_make_scale(state["zz25"]),
            zz50=_make_scale(state["zz50"]),
            zz75=_make_scale(state["zz75"])
        )


# Global singleton instance
sv5_turbulence_lookup = SV5TurbulenceLookupAdapter()
