"""
Alert Entity — Domain Model
==============================
Pure domain entity for system-wide alerts generated by the vault daemon
when critical thresholds are crossed (VIX regime shifts, Net Liquidity
changes, SEC material events, moat decay signals).

No framework imports. No infrastructure dependencies.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Alert:
    """A single actionable alert generated by the surveillance system."""
    category: str          # vix, macro, sec, moat, flow
    severity: str          # info, warning, critical
    ticker: str            # ticker or "MARKET" for macro
    title: str             # Short headline
    message: str           # Detailed description
    source: str            # vault function that generated it
    timestamp: str = ""    # ISO 8601

    # Optional context
    metric_name: Optional[str] = None    # e.g. "vix", "net_liquidity"
    metric_value: Optional[float] = None # e.g. 32.5
    previous_value: Optional[float] = None
    threshold: Optional[float] = None

    # Lifecycle
    acknowledged: bool = False
    resolved: bool = False

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.utcnow().isoformat()


@dataclass
class InstrumentHealth:
    """Progressive health status for a single instrument.

    Replaces binary blacklisting with a 4-level degradation system:
      HEALTHY  → full allocation, all gates pass
      ALERT    → reduced sizing (0.5x), flag for review
      WOUNDED  → no new entries, hold existing
      DEATH    → force exit, 4Q cooldown

    Health can RECOVER: WOUNDED → ALERT → HEALTHY over time
    if the triggering condition resolves (e.g., 8-K was benign,
    margin recovered, insider selling stopped).
    """
    ticker: str
    department: str        # QUALITY or SPECULATIVE
    status: str = "HEALTHY"  # HEALTHY, ALERT, WOUNDED, DEATH
    reasons: list = field(default_factory=list)
    moat_risk: int = 0     # 0-100 from SEC 8-K analysis
    margin_decay_pct: float = 0.0  # Operating margin decline %
    insider_signal: str = "neutral"
    last_updated: str = ""

    def __post_init__(self):
        if not self.last_updated:
            self.last_updated = datetime.utcnow().isoformat()

    @property
    def sizing_multiplier(self) -> float:
        """Position sizing multiplier based on health status."""
        return {
            "HEALTHY": 1.0,
            "ALERT": 0.5,
            "WOUNDED": 0.0,
            "DEATH": 0.0,
        }.get(self.status, 1.0)

    @property
    def allows_new_entry(self) -> bool:
        return self.status in ("HEALTHY", "ALERT")

    @property
    def requires_exit(self) -> bool:
        return self.status == "DEATH"
