/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'user-avatar': UserAvatar;
    portfolios: Portfolio;
    'portfolio-memberships': PortfolioMembership;
    'broker-accounts': BrokerAccount;
    'mcp-servers': McpServer;
    'agent-skills': AgentSkill;
    bots: Bot;
    'bot-assignments': BotAssignment;
    instruments: Instrument;
    'regime-phases': RegimePhase;
    'calibration-profiles': CalibrationProfile;
    'candidate-screenings': CandidateScreening;
    'trade-snapshots': TradeSnapshot;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    portfolios: {
      brokerAccounts: 'broker-accounts';
      bots: 'bots';
      members: 'portfolio-memberships';
    };
    bots: {
      assignments: 'bot-assignments';
    };
    instruments: {
      regimePhases: 'regime-phases';
      screenings: 'candidate-screenings';
      calibrations: 'calibration-profiles';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'user-avatar': UserAvatarSelect<false> | UserAvatarSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    'portfolio-memberships': PortfolioMembershipsSelect<false> | PortfolioMembershipsSelect<true>;
    'broker-accounts': BrokerAccountsSelect<false> | BrokerAccountsSelect<true>;
    'mcp-servers': McpServersSelect<false> | McpServersSelect<true>;
    'agent-skills': AgentSkillsSelect<false> | AgentSkillsSelect<true>;
    bots: BotsSelect<false> | BotsSelect<true>;
    'bot-assignments': BotAssignmentsSelect<false> | BotAssignmentsSelect<true>;
    instruments: InstrumentsSelect<false> | InstrumentsSelect<true>;
    'regime-phases': RegimePhasesSelect<false> | RegimePhasesSelect<true>;
    'calibration-profiles': CalibrationProfilesSelect<false> | CalibrationProfilesSelect<true>;
    'candidate-screenings': CandidateScreeningsSelect<false> | CandidateScreeningsSelect<true>;
    'trade-snapshots': TradeSnapshotsSelect<false> | TradeSnapshotsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * User profile avatars and profile pictures
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-avatar".
 */
export interface UserAvatar {
  id: number;
  alt?: string | null;
  user: number | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  nickname?: string | null;
  preferredLanguage?: ('en' | 'es') | null;
  authProvider?: ('payload' | 'google') | null;
  passwordSetAt?: string | null;
  otpCode?: string | null;
  otpExpiry?: string | null;
  otpAttempts?: number | null;
  login_count?: number | null;
  avatar?: (number | null) | UserAvatar;
  role: 'superadmin' | 'admin' | 'user';
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  name: string;
  /**
   * Auto-generated. Cannot be changed.
   */
  slug?: string | null;
  status: 'active' | 'suspended' | 'archived';
  owner: number | User;
  brokerAccounts?: {
    docs?: (number | BrokerAccount)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  bots?: {
    docs?: (number | Bot)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  members?: {
    docs?: (number | PortfolioMembership)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broker-accounts".
 */
export interface BrokerAccount {
  id: number;
  portfolio: number | Portfolio;
  name: string;
  brokerType: 'alpaca' | 'interactive_brokers';
  environment: 'paper' | 'live';
  isActive?: boolean | null;
  /**
   * Required for Alpaca. Enter your API Key here.
   */
  apiKeyPlaintext?: string | null;
  /**
   * Your API key (last 4 digits only for security).
   */
  apiKeyMasked?: string | null;
  /**
   * Required for Alpaca. Enter your Secret Key here.
   */
  secretKeyPlaintext?: string | null;
  /**
   * Your secret key (last 4 digits only for security).
   */
  secretKeyMasked?: string | null;
  /**
   * Required for Interactive Brokers. Your IB Account ID.
   */
  ibAccountId?: string | null;
  /**
   * Alpaca API base URL (defaults to paper trading URL).
   */
  alpacaBaseUrl?: string | null;
  /**
   * Interactive Brokers host (e.g., 127.0.0.1).
   */
  ibHost?: string | null;
  /**
   * Interactive Brokers port.
   */
  ibPort?: number | null;
  /**
   * Interactive Brokers client ID.
   */
  ibClientId?: number | null;
  /**
   * View all bots assigned to this broker account in Portfolio > Bot Assignments. Manage bot-to-account mappings at the portfolio level for a complete deployment strategy.
   */
  botsInfo?: string | null;
  apiKeyEncrypted?: string | null;
  apiKeyIv?: string | null;
  apiKeyAuthTag?: string | null;
  secretKeyEncrypted?: string | null;
  secretKeyIv?: string | null;
  secretKeyAuthTag?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bots".
 */
export interface Bot {
  id: number;
  name: string;
  /**
   * Public identifier for agent URLs (auto-generated).
   */
  botSlug?: string | null;
  portfolio: number | Portfolio;
  /**
   * AI Agent = Claude-powered. Strategy = traditional algorithm running in the Python backend.
   */
  executionType: 'agent' | 'strategy';
  strategyType: 'qgarp' | 'momentum' | 'mean_reversion' | 'trend_following' | 'custom';
  status: 'active' | 'paused' | 'stopped' | 'error';
  description?: string | null;
  /**
   * Strategy-specific configuration (parameters, thresholds, filters).
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claude Agent ID (auto-synced on save).
   */
  agentId?: string | null;
  /**
   * Current agent version in Anthropic.
   */
  agentVersion?: number | null;
  agentSyncStatus?: ('not_created' | 'synced' | 'pending' | 'error') | null;
  agentSyncError?: string | null;
  /**
   * Which Claude model powers this agent.
   */
  model?: ('claude-opus-4-7' | 'claude-sonnet-4-6' | 'claude-haiku-4') | null;
  /**
   * The system prompt that defines this agent's behavior and expertise.
   */
  systemPrompt?: string | null;
  /**
   * Select which MCP servers this agent can access.
   */
  mcpServers?: (number | McpServer)[] | null;
  /**
   * Select which skills this agent has.
   */
  skills?: (number | AgentSkill)[] | null;
  /**
   * Arbitrary metadata stored on the Claude agent.
   */
  agentMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  assignments?: {
    docs?: (number | BotAssignment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-servers".
 */
export interface McpServer {
  id: number;
  /**
   * Display name (e.g., "Alpaca Trading", "Yahoo Finance").
   */
  name: string;
  /**
   * Auto-generated identifier used in agent configs.
   */
  slug?: string | null;
  /**
   * What capabilities does this MCP provide?
   */
  description?: string | null;
  /**
   * Only "URL" works with Claude Cloud agents.
   */
  type: 'url' | 'stdio';
  /**
   * Remote MCP endpoint (e.g., https://mcp.example.com/mcp).
   */
  url?: string | null;
  category: 'broker' | 'data' | 'analytics' | 'macro' | 'news';
  /**
   * Disable to prevent agents from using this MCP.
   */
  isActive?: boolean | null;
  defaultPermissionPolicy?: ('always_allow' | 'ask_user') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-skills".
 */
export interface AgentSkill {
  id: number;
  /**
   * Skill name (e.g., "Fundamental Analyst", "Web Search").
   */
  name: string;
  /**
   * Auto-generated identifier.
   */
  slug?: string | null;
  /**
   * What capability does this skill give the agent?
   */
  description?: string | null;
  /**
   * Built-in: Anthropic-provided skill. Custom: prompt injected into system prompt.
   */
  type: 'builtin' | 'custom';
  category: 'analysis' | 'execution' | 'risk' | 'research' | 'general';
  isActive?: boolean | null;
  /**
   * Anthropic skill ID (e.g., "web_search"). Only for built-in type.
   */
  builtinId?: string | null;
  /**
   * Skill instructions injected into the agent system prompt.
   */
  promptContent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bot-assignments".
 */
export interface BotAssignment {
  id: number;
  /**
   * Portfolio this bot assignment belongs to.
   */
  portfolio: number | Portfolio;
  /**
   * The bot strategy to deploy.
   */
  bot: number | Bot;
  /**
   * The broker account where this bot will execute.
   */
  brokerAccount: number | BrokerAccount;
  /**
   * Enable this bot on the selected broker account.
   */
  isActive?: boolean | null;
  riskLimits?: {
    /**
     * Max % of portfolio value per position.
     */
    maxPositionSize?: number | null;
    /**
     * Max daily loss % before bot auto-pauses.
     */
    maxDailyLoss?: number | null;
    /**
     * Max concurrent open positions.
     */
    maxOpenPositions?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-memberships".
 */
export interface PortfolioMembership {
  id: number;
  portfolio: number | Portfolio;
  user: number | User;
  portfolioRole: 'owner' | 'admin' | 'trader' | 'viewer';
  invitedBy?: (number | null) | User;
  joinedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruments".
 */
export interface Instrument {
  id: number;
  /**
   * Ticker symbol (e.g., AAPL, XLK, SPY)
   */
  ticker: string;
  /**
   * Full instrument name
   */
  name: string;
  instrumentType: 'stock' | 'etf_sector' | 'etf_international' | 'etf_commodity' | 'index';
  /**
   * GICS sector classification
   */
  gicsSector?:
    | (
        | 'information_technology'
        | 'health_care'
        | 'financials'
        | 'consumer_discretionary'
        | 'consumer_staples'
        | 'industrials'
        | 'energy'
        | 'utilities'
        | 'real_estate'
        | 'materials'
        | 'communication_services'
      )
    | null;
  /**
   * GICS industry (e.g., Semiconductors)
   */
  gicsIndustry?: string | null;
  /**
   * GICS sub-industry (e.g., Semiconductor Equipment)
   */
  gicsSubIndustry?: string | null;
  /**
   * Parent sector ETF (e.g., AAPL → XLK)
   */
  sectorETF?: (number | null) | Instrument;
  universe?: ('sp500' | 'domestic_sector' | 'international' | 'commodity' | 'guru_gem') | null;
  cyclicalType?: ('cyclical' | 'defensive' | 'mixed') | null;
  marketCap?: ('mega' | 'large' | 'mid' | 'small') | null;
  isActive?: boolean | null;
  isInSP500?: boolean | null;
  /**
   * Latest fundamental metrics (QGARP, Piotroski, Altman Z, FCF Margin, etc.)
   */
  lastFundamentals?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When fundamentals were last refreshed
   */
  fundamentalsUpdatedAt?: string | null;
  /**
   * Next earnings report date — triggers fundamental refresh
   */
  nextEarningsDate?: string | null;
  regimePhases?: {
    docs?: (number | RegimePhase)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  screenings?: {
    docs?: (number | CandidateScreening)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  calibrations?: {
    docs?: (number | CalibrationProfile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Owning portfolio (tenant)
   */
  portfolio?: (number | null) | Portfolio;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regime-phases".
 */
export interface RegimePhase {
  id: number;
  /**
   * Instrument this phase belongs to (SPY for market, XLK for sector, AAPL for instrument)
   */
  instrument: number | Instrument;
  level: 'market' | 'sector' | 'instrument';
  phase: 'accumulation' | 'markup' | 'distribution' | 'markdown';
  /**
   * When this phase transition was detected
   */
  detectedAt: string;
  /**
   * When this phase ended (null = currently active)
   */
  closedAt?: string | null;
  /**
   * Duration in days (calculated when phase closes)
   */
  durationDays?: number | null;
  /**
   * VIX level when phase was detected
   */
  vixAtDetection?: number | null;
  /**
   * % of stocks above 50-DMA at detection
   */
  breadthAtDetection?: number | null;
  /**
   * Relative volume at detection time
   */
  relativeVolumeAtDetection?: number | null;
  /**
   * What signal triggered the phase change (e.g., CHoCH_BULLISH, VIX_CROSSOVER_25)
   */
  triggerSignal?: string | null;
  /**
   * Previous phase in the chain (for historical tracking)
   */
  previousPhase?: (number | null) | RegimePhase;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-screenings".
 */
export interface CandidateScreening {
  id: number;
  instrument: number | Instrument;
  category: 'core_hohn' | 'core_dividend' | 'tactical_spring' | 'tactical_momentum';
  /**
   * Market regime at screening time
   */
  marketRegime?: (number | null) | RegimePhase;
  /**
   * Sector regime at screening time
   */
  sectorRegime?: (number | null) | RegimePhase;
  /**
   * Hohn/Munger composite conviction score
   */
  compositeScore: number;
  qgarpScore?: number | null;
  fcfMargin?: number | null;
  piotroskiFScore?: number | null;
  /**
   * Price / GF Value ratio (< 1 = undervalued)
   */
  priceToGFValue?: number | null;
  guruConviction?: number | null;
  insiderConviction?: number | null;
  /**
   * Beneish M-Score (> -1.78 = manipulation risk)
   */
  beneishM?: number | null;
  /**
   * Altman Z-Score (< 1.81 = distress zone)
   */
  altmanZ?: number | null;
  /**
   * When this ticker passed the screening filter
   */
  enteredAt: string;
  /**
   * When this ticker stopped passing the filter
   */
  exitedAt?: string | null;
  exitReason?:
    | ('score_decay' | 'beneish_flag' | 'altman_distress' | 'regime_change' | 'manual' | 'positioned' | 'superseded')
    | null;
  status: 'active' | 'expired' | 'positioned' | 'closed';
  portfolio?: (number | null) | Portfolio;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calibration-profiles".
 */
export interface CalibrationProfile {
  id: number;
  instrument: number | Instrument;
  category: 'core_hohn' | 'core_dividend' | 'tactical_spring' | 'tactical_momentum';
  /**
   * Market-level regime when this calibration was trained
   */
  marketRegime?: (number | null) | RegimePhase;
  /**
   * Sector-level regime when this calibration was trained
   */
  sectorRegime?: (number | null) | RegimePhase;
  /**
   * Instrument-level regime when this calibration was trained
   */
  instrumentRegime?: (number | null) | RegimePhase;
  /**
   * Array of {name, weight, ceiling_sharpe} — calibrated signal weights
   */
  signals:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Composite Sharpe ratio of the calibrated strategy
   */
  compositeSharpe?: number | null;
  /**
   * Win rate percentage of the calibrated strategy
   */
  winRate?: number | null;
  /**
   * Number of trades in the calibration backtest
   */
  totalTrades?: number | null;
  trainedAt: string;
  /**
   * Start of OHLCV data used for calibration
   */
  dataRangeFrom?: string | null;
  /**
   * End of OHLCV data used for calibration
   */
  dataRangeTo?: string | null;
  /**
   * Parent calibration used as warm-start (initial weights)
   */
  warmStartFrom?: (number | null) | CalibrationProfile;
  /**
   * Diff of signal weights vs parent — shows how much changed
   */
  warmStartDelta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'active' | 'superseded' | 'invalidated';
  /**
   * The regime change that invalidated this calibration
   */
  invalidatedBy?: (number | null) | RegimePhase;
  invalidatedAt?: string | null;
  portfolio?: (number | null) | Portfolio;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-snapshots".
 */
export interface TradeSnapshot {
  id: number;
  instrument: number | Instrument;
  /**
   * Candidate screening that originated this trade evaluation
   */
  screening?: (number | null) | CandidateScreening;
  /**
   * Calibration profile used for signal weights
   */
  calibration?: (number | null) | CalibrationProfile;
  marketRegime?: (number | null) | RegimePhase;
  sectorRegime?: (number | null) | RegimePhase;
  instrumentRegime?: (number | null) | RegimePhase;
  /**
   * Whether the PreTradeGate approved this trade
   */
  gateApproved?: boolean | null;
  /**
   * Reason for gate approval/rejection
   */
  gateReason?: string | null;
  compositeScore?: number | null;
  /**
   * Snapshot of all signal values at evaluation time
   */
  signals?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * SMC analysis result (BOS, CHoCH, OB, FVG)
   */
  structureResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  side?: ('long' | 'short') | null;
  strategy?: ('core' | 'tactical') | null;
  entryPrice?: number | null;
  stopPrice?: number | null;
  targetPrice?: number | null;
  exitPrice?: number | null;
  exitReason?: ('target_hit' | 'stop_hit' | 'manual' | 'thesis_broke' | 'time_decay' | 'regime_change') | null;
  /**
   * Profit/Loss percentage
   */
  pnlPct?: number | null;
  openedAt?: string | null;
  closedAt?: string | null;
  portfolio?: (number | null) | Portfolio;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'user-avatar';
        value: number | UserAvatar;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'portfolio-memberships';
        value: number | PortfolioMembership;
      } | null)
    | ({
        relationTo: 'broker-accounts';
        value: number | BrokerAccount;
      } | null)
    | ({
        relationTo: 'mcp-servers';
        value: number | McpServer;
      } | null)
    | ({
        relationTo: 'agent-skills';
        value: number | AgentSkill;
      } | null)
    | ({
        relationTo: 'bots';
        value: number | Bot;
      } | null)
    | ({
        relationTo: 'bot-assignments';
        value: number | BotAssignment;
      } | null)
    | ({
        relationTo: 'instruments';
        value: number | Instrument;
      } | null)
    | ({
        relationTo: 'regime-phases';
        value: number | RegimePhase;
      } | null)
    | ({
        relationTo: 'calibration-profiles';
        value: number | CalibrationProfile;
      } | null)
    | ({
        relationTo: 'candidate-screenings';
        value: number | CandidateScreening;
      } | null)
    | ({
        relationTo: 'trade-snapshots';
        value: number | TradeSnapshot;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-avatar_select".
 */
export interface UserAvatarSelect<T extends boolean = true> {
  alt?: T;
  user?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  owner?: T;
  brokerAccounts?: T;
  bots?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-memberships_select".
 */
export interface PortfolioMembershipsSelect<T extends boolean = true> {
  portfolio?: T;
  user?: T;
  portfolioRole?: T;
  invitedBy?: T;
  joinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broker-accounts_select".
 */
export interface BrokerAccountsSelect<T extends boolean = true> {
  portfolio?: T;
  name?: T;
  brokerType?: T;
  environment?: T;
  isActive?: T;
  apiKeyPlaintext?: T;
  apiKeyMasked?: T;
  secretKeyPlaintext?: T;
  secretKeyMasked?: T;
  ibAccountId?: T;
  alpacaBaseUrl?: T;
  ibHost?: T;
  ibPort?: T;
  ibClientId?: T;
  botsInfo?: T;
  apiKeyEncrypted?: T;
  apiKeyIv?: T;
  apiKeyAuthTag?: T;
  secretKeyEncrypted?: T;
  secretKeyIv?: T;
  secretKeyAuthTag?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-servers_select".
 */
export interface McpServersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  url?: T;
  category?: T;
  isActive?: T;
  defaultPermissionPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-skills_select".
 */
export interface AgentSkillsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  category?: T;
  isActive?: T;
  builtinId?: T;
  promptContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bots_select".
 */
export interface BotsSelect<T extends boolean = true> {
  name?: T;
  botSlug?: T;
  portfolio?: T;
  executionType?: T;
  strategyType?: T;
  status?: T;
  description?: T;
  config?: T;
  agentId?: T;
  agentVersion?: T;
  agentSyncStatus?: T;
  agentSyncError?: T;
  model?: T;
  systemPrompt?: T;
  mcpServers?: T;
  skills?: T;
  agentMetadata?: T;
  assignments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bot-assignments_select".
 */
export interface BotAssignmentsSelect<T extends boolean = true> {
  portfolio?: T;
  bot?: T;
  brokerAccount?: T;
  isActive?: T;
  riskLimits?:
    | T
    | {
        maxPositionSize?: T;
        maxDailyLoss?: T;
        maxOpenPositions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruments_select".
 */
export interface InstrumentsSelect<T extends boolean = true> {
  ticker?: T;
  name?: T;
  instrumentType?: T;
  gicsSector?: T;
  gicsIndustry?: T;
  gicsSubIndustry?: T;
  sectorETF?: T;
  universe?: T;
  cyclicalType?: T;
  marketCap?: T;
  isActive?: T;
  isInSP500?: T;
  lastFundamentals?: T;
  fundamentalsUpdatedAt?: T;
  nextEarningsDate?: T;
  regimePhases?: T;
  screenings?: T;
  calibrations?: T;
  portfolio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regime-phases_select".
 */
export interface RegimePhasesSelect<T extends boolean = true> {
  instrument?: T;
  level?: T;
  phase?: T;
  detectedAt?: T;
  closedAt?: T;
  durationDays?: T;
  vixAtDetection?: T;
  breadthAtDetection?: T;
  relativeVolumeAtDetection?: T;
  triggerSignal?: T;
  previousPhase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calibration-profiles_select".
 */
export interface CalibrationProfilesSelect<T extends boolean = true> {
  instrument?: T;
  category?: T;
  marketRegime?: T;
  sectorRegime?: T;
  instrumentRegime?: T;
  signals?: T;
  compositeSharpe?: T;
  winRate?: T;
  totalTrades?: T;
  trainedAt?: T;
  dataRangeFrom?: T;
  dataRangeTo?: T;
  warmStartFrom?: T;
  warmStartDelta?: T;
  status?: T;
  invalidatedBy?: T;
  invalidatedAt?: T;
  portfolio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-screenings_select".
 */
export interface CandidateScreeningsSelect<T extends boolean = true> {
  instrument?: T;
  category?: T;
  marketRegime?: T;
  sectorRegime?: T;
  compositeScore?: T;
  qgarpScore?: T;
  fcfMargin?: T;
  piotroskiFScore?: T;
  priceToGFValue?: T;
  guruConviction?: T;
  insiderConviction?: T;
  beneishM?: T;
  altmanZ?: T;
  enteredAt?: T;
  exitedAt?: T;
  exitReason?: T;
  status?: T;
  portfolio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-snapshots_select".
 */
export interface TradeSnapshotsSelect<T extends boolean = true> {
  instrument?: T;
  screening?: T;
  calibration?: T;
  marketRegime?: T;
  sectorRegime?: T;
  instrumentRegime?: T;
  gateApproved?: T;
  gateReason?: T;
  compositeScore?: T;
  signals?: T;
  structureResult?: T;
  side?: T;
  strategy?: T;
  entryPrice?: T;
  stopPrice?: T;
  targetPrice?: T;
  exitPrice?: T;
  exitReason?: T;
  pnlPct?: T;
  openedAt?: T;
  closedAt?: T;
  portfolio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  nickname?: T;
  preferredLanguage?: T;
  authProvider?: T;
  passwordSetAt?: T;
  otpCode?: T;
  otpExpiry?: T;
  otpAttempts?: T;
  login_count?: T;
  avatar?: T;
  role?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  /**
   * Add up to 6 legal/legislative policy links (e.g., Privacy, Terms, Cookies). These will be rendered in the footer and mobile menu. If there are more than 2, footer will show first 2 and an Other policies link.
   */
  legalPolicies?:
    | {
        name: string;
        label?: string | null;
        type: 'reference' | 'custom';
        reference?: {
          relationTo: 'portfolios';
          value: number | Portfolio;
        } | null;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  branding: {
    /**
     * Used as fallback when logo is not available
     */
    siteName?: string | null;
    /**
     * Choose how you want to configure your logos
     */
    logoMode: 'simple' | 'lightDark';
    logo?: (number | null) | Media;
    logoLight?: (number | null) | Media;
    logoDark?: (number | null) | Media;
    /**
     * Upload your favicon (the small icon displayed in browser tabs). Recommended: 32x32px PNG or ICO file.
     */
    favicon?: (number | null) | Media;
    /**
     * Upload a logo specifically for the admin panel.
     */
    adminLogo?: (number | null) | Media;
  };
  themeSettings: {
    /**
     * Choose whether your site supports light theme, dark theme, or both
     */
    themeMode: 'light-only' | 'dark-only' | 'both';
    /**
     * Choose the default theme when users first visit your site
     */
    defaultTheme?: ('light' | 'dark' | 'system') | null;
    /**
     * Enable this to customize primary and secondary colors for your site
     */
    customColors?: boolean | null;
    /**
     * Choose your primary brand color. This will be automatically adjusted for light and dark themes.
     */
    primaryColor?: string | null;
    /**
     * Choose your secondary color. This will be automatically adjusted for light and dark themes.
     */
    secondaryColor?: string | null;
    /**
     * Enable this to customize fonts for headings and body text
     */
    customFonts?: boolean | null;
    typography?: {};
  };
  socialMedia?: {
    platforms?:
      | {
          platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'github' | 'discord';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * When disabled, new public users cannot sign up and the Sign up option is hidden from login.
   */
  allowNewUsers?: boolean | null;
  seo?: {
    /**
     * Default meta description for pages that don't have one set
     */
    siteDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  legalPolicies?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  branding?:
    | T
    | {
        siteName?: T;
        logoMode?: T;
        logo?: T;
        logoLight?: T;
        logoDark?: T;
        favicon?: T;
        adminLogo?: T;
      };
  themeSettings?:
    | T
    | {
        themeMode?: T;
        defaultTheme?: T;
        customColors?: T;
        primaryColor?: T;
        secondaryColor?: T;
        customFonts?: T;
        typography?: T | {};
      };
  socialMedia?:
    | T
    | {
        platforms?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  allowNewUsers?: T;
  seo?:
    | T
    | {
        siteDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}